<a href="https://colab.research.google.com/github/iagoslopes/Mineracao_Dados-Iago/blob/master/C%C3%B3pia_de_Aula02_NumPy_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

![image.png]()

# Revendo aula passada

In [1]:
dados = [50,50,47,97,49,3,53,42,26,74,82,62,37,15,70,27,36,35,48,52,63,64]
print(dados)

[50, 50, 47, 97, 49, 3, 53, 42, 26, 74, 82, 62, 37, 15, 70, 27, 36, 35, 48, 52, 63, 64]

Os dados foram carregados em uma estrutura de lista Python, que é um bom tipo de dados para manipulação geral de dados, mas não é otimizado para análise numérica. Para isso, usaremos o pacote NumPy, que inclui tipos de dados e funções específicas para trabalhar com Numbers em Python.

In [2]:
import numpy as np

valores = np.array(dados)
print(valores)

[50 50 47 97 49  3 53 42 26 74 82 62 37 15 70 27 36 35 48 52 63 64]

In [3]:
valores

array([50, 50, 47, 97, 49,  3, 53, 42, 26, 74, 82, 62, 37, 15, 70, 27, 36,
       35, 48, 52, 63, 64])

Visualizar a forma da matriz

In [4]:
valores.shape

(22,)

A forma confirma que esta matriz possui apenas uma dimensão, que contém 22 elementos. (Existem 22 notas na lista original.) Você pode acessar os elementos individuais na matriz por sua posição ordinal baseada em zero. Vamos pegar o primeiro elemento (aquele na posição 0).

In [6]:
valores[4]

49

Você pode aplicar agregações entre os elementos da matriz, então vamos encontrar a nota média simples (em outras palavras, o valor da nota média).

In [7]:
valores.mean()

49.18181818181818

Vamos adicionar um segundo conjunto de dados para os mesmos alunos. Desta vez, registraremos o número típico de horas semanais que eles dedicam ao estudo.

In [8]:
# Notas dos alunos criada anteriormente
valores

array([50, 50, 47, 97, 49,  3, 53, 42, 26, 74, 82, 62, 37, 15, 70, 27, 36,
       35, 48, 52, 63, 64])

In [9]:
# Define um array de horas de estudo
estudo_horas = [10.0,11.5,9.0,16.0,9.25,1.0,11.5,9.0,8.5,14.5,15.5,
               13.75,9.0,8.0,15.5,8.0,9.0,6.0,10.0,12.0,12.5,12.0]

# Criar um array 2D (um array de arrays)
estudantes_data = np.array([estudo_horas, valores])

# mostrar o array
estudantes_data

array([[10.  , 11.5 ,  9.  , 16.  ,  9.25,  1.  , 11.5 ,  9.  ,  8.5 ,
        14.5 , 15.5 , 13.75,  9.  ,  8.  , 15.5 ,  8.  ,  9.  ,  6.  ,
        10.  , 12.  , 12.5 , 12.  ],
       [50.  , 50.  , 47.  , 97.  , 49.  ,  3.  , 53.  , 42.  , 26.  ,
        74.  , 82.  , 62.  , 37.  , 15.  , 70.  , 27.  , 36.  , 35.  ,
        48.  , 52.  , 63.  , 64.  ]])

In [10]:
estudantes_data.shape

(2, 22)

Para navegar nesta estrutura, você precisa especificar a posição de cada elemento na hierarquia. Portanto, para encontrar o primeiro valor na primeira matriz (que contém os dados das horas de estudo), você pode usar o código a seguir.

In [11]:
# Mostra o primeiro elemento da primeira dimensão
estudantes_data[0][0]

10.0

Agora você tem uma matriz multidimensional contendo o tempo de estudo do aluno e informações sobre a nota, que pode ser usada para comparar o tempo de estudo com a nota do aluno.

In [12]:
# Pega a media de valores de cada sub-array
media_estudo = estudantes_data[0].mean()
media_notas = estudantes_data[1].mean()

print('Media de horas de estudo: {:.2f}\nMedia de Notas: {:.2f}'.format(media_estudo, media_notas))

Media de horas de estudo: 10.52
Media de Notas: 49.18

# **Explorando dados tabulares com Pandas**

NumPy fornece muitas funcionalidades e ferramentas necessárias para trabalhar com números, como matrizes de valores numéricos. Porém, quando você começa a lidar com tabelas de dados bidimensionais, o pacote Pandas oferece uma estrutura mais conveniente para trabalhar: o DataFrame.

https://pandas.pydata.org/

## **Importando o Pandas**

In [13]:
import pandas as pd

## **Tipos de dados**

O Pandas possui dois tipos de dados principais, Series e DataFrame. Séries são dados em uma única dimensão (coluna), já os DataFrames representam uma tabela de dados e possuem duas dimensões (linhas e colunas).

## Series

Você pode criar uma Séries usando pd.Series() e passando uma lista Python:

In [14]:
carros = pd.Series(["Toyota", "Honda", "BMW"])
cores = pd.Series(["Azul", "Branco", "Vermelho"])

In [15]:
carros

0    Toyota
1     Honda
2       BMW
dtype: object

In [16]:
cores

0        Azul
1      Branco
2    Vermelho
dtype: object

## DataFrame
Para criar um DataFrame utilizamos pd.DataFrame() passando um dicionário Python como parâmetro:

In [19]:
df = pd.DataFrame({"Fabricante": carros,"Cores": cores})
df

  Fabricante     Cores
0     Toyota      Azul
1      Honda    Branco
2        BMW  Vermelho

Como podemos observar ao criar o DataFrame informamos um dicionário Python e geramos uma tabela de linhas e colunas onde as chaves do dicionário se tornaram os títulos das colunas e os valores das duas Séries se tornaram os dados no DataFrame.

# **Explorando dados tabulares com Pandas**

NumPy fornece muitas funcionalidades e ferramentas necessárias para trabalhar com números, como matrizes de valores numéricos. Porém, quando você começa a lidar com tabelas de dados bidimensionais, o pacote Pandas oferece uma estrutura mais conveniente para trabalhar: o DataFrame.

Execute a célula a seguir para importar a biblioteca Pandas e criar um DataFrame com três colunas. A primeira coluna é uma lista de nomes de alunos e a segunda e terceira colunas são as matrizes NumPy contendo o tempo de estudo e os dados das notas.

In [20]:
df_estudantes = pd.DataFrame({'Nome': ['Dan', 'Joann', 'Pedro', 'Rosie', 'Ethan', 'Vicky', 'Frederic', 'Jimmie',
                                     'Rhonda', 'Giovanni', 'Francesca', 'Rajab', 'Naiyana', 'Kian', 'Jenny',
                                     'Jakeem','Helena','Ismat','Anila','Skye','Daniel','Aisha'],
                            'HorasEstudo':estudantes_data[0],
                            'Notas':estudantes_data[1]})

df_estudantes

         Nome  HorasEstudo  Notas
0         Dan        10.00   50.0
1       Joann        11.50   50.0
2       Pedro         9.00   47.0
3       Rosie        16.00   97.0
4       Ethan         9.25   49.0
5       Vicky         1.00    3.0
6    Frederic        11.50   53.0
7      Jimmie         9.00   42.0
8      Rhonda         8.50   26.0
9    Giovanni        14.50   74.0
10  Francesca        15.50   82.0
11      Rajab        13.75   62.0
12    Naiyana         9.00   37.0
13       Kian         8.00   15.0
14      Jenny        15.50   70.0
15     Jakeem         8.00   27.0
16     Helena         9.00   36.0
17      Ismat         6.00   35.0
18      Anila        10.00   48.0
19       Skye        12.00   52.0
20     Daniel        12.50   63.0
21      Aisha        12.00   64.0

Observe que além das colunas especificadas, o DataFrame inclui um índice para identificar exclusivamente cada linha. Poderíamos ter especificado o índice explicitamente e atribuído qualquer tipo de valor apropriado (por exemplo, um endereço de e-mail). No entanto, como não especificamos um índice, foi criado um com um valor inteiro exclusivo para cada linha.

## **Encontrar e filtrar dados em um DataFrame**

loc

iloc

Você pode usar o método loc do DataFrame para recuperar dados para um valor de índice específico, como este.

In [21]:
# Pega os dados por índice com valor 5
df_estudantes.loc[5]

Nome           Vicky
HorasEstudo      1.0
Notas            3.0
Name: 5, dtype: object

Você também pode obter os dados em vários valores de índice, como este:

In [22]:
# Pega as linhas com índice de 0 a 5
df_estudantes.loc[0:5]

    Nome  HorasEstudo  Notas
0    Dan        10.00   50.0
1  Joann        11.50   50.0
2  Pedro         9.00   47.0
3  Rosie        16.00   97.0
4  Ethan         9.25   49.0
5  Vicky         1.00    3.0

Além de poder usar o método loc para encontrar linhas com base no índice, você pode usar o método iloc para encontrar linhas com base em sua posição ordinal no DataFrame (independentemente do índice):

In [23]:
# Pega dados das primeiras 5 linhas
df_estudantes.iloc[0:5]

    Nome  HorasEstudo  Notas
0    Dan        10.00   50.0
1  Joann        11.50   50.0
2  Pedro         9.00   47.0
3  Rosie        16.00   97.0
4  Ethan         9.25   49.0

Observe atentamente os resultados do iloc[0:5] e compare-os com os resultados do loc[0:5] obtidos anteriormente. Você pode ver a diferença?

O método loc retornou linhas com rótulo de índice na lista de valores de 0 a 5, que inclui 0, 1, 2, 3, 4 e 5 (seis linhas). No entanto, o método iloc retorna as linhas nas posições incluídas no intervalo de 0 a 5. Como os intervalos de números inteiros não incluem o valor do limite superior, isso inclui as posições 0, 1, 2, 3 e 4 (cinco linhas).

O iloc identifica valores de dados em um DataFrame por posição, que se estende além das linhas até as colunas. Então, por exemplo, você pode usá-lo para encontrar os valores das colunas nas posições 1 e 2 da linha 0, assim:

In [24]:
df_estudantes.iloc[0,[1,2]]

HorasEstudo    10.0
Notas          50.0
Name: 0, dtype: object

Vamos voltar ao método loc e ver como ele funciona com colunas. Lembre-se de que você usa loc para localizar itens de dados com base em valores de índice em vez de posições. Na ausência de uma coluna de índice explícita, as linhas no nosso DataFrame são indexadas como valores inteiros, mas as colunas são identificadas pelo nome:

In [25]:
df_estudantes.loc[0,'Notas']

50.0

Aqui está outro truque útil. Você pode usar o método loc para localizar linhas indexadas com base em uma expressão de filtragem que faz referência a colunas nomeadas diferentes do índice, como esta:

In [26]:
df_estudantes.loc[df_estudantes['Nome']=='Aisha']

     Nome  HorasEstudo  Notas
21  Aisha         12.0   64.0

Na verdade, você não precisa usar explicitamente o método loc para fazer isso. Você pode simplesmente aplicar uma expressão de filtragem DataFrame, como esta:

In [27]:
df_estudantes[df_estudantes['Nome']=='Aisha']

     Nome  HorasEstudo  Notas
21  Aisha         12.0   64.0

E para garantir, você pode obter os mesmos resultados usando o método query do DataFrame, assim:

In [28]:
df_estudantes.query('Nome=="Aisha"')

     Nome  HorasEstudo  Notas
21  Aisha         12.0   64.0

Os três exemplos anteriores sublinham uma verdade confusa sobre como trabalhar com Pandas. Freqüentemente, existem várias maneiras de obter os mesmos resultados. Outro exemplo disso é a maneira como você se refere ao nome de uma coluna DataFrame. Você pode especificar o nome da coluna como um valor de índice nomeado (como nos exemplos df_students['Name'] que vimos até agora), ou você pode usar a coluna como uma propriedade do DataFrame, assim:

In [29]:
df_estudantes[df_estudantes.Nome == 'Aisha']

     Nome  HorasEstudo  Notas
21  Aisha         12.0   64.0

# **Manipulando dados com Pandas - Outras fontes**

Como vimos anteriormente, criar Séries e DataFrame do zero é legal, mas normalmente faremos a importação dos dados no formato de um arquivo `.csv` ou planilha.

O Pandas permite a importação de dados de maneira fácil por meio de funções como `pd.read_csv()` e `pd.read_excel()`.

Por exemplo, vamos obter as informações deste endereço do github:

In [30]:
# importando os dados de venda de carros
df_carros = pd.read_csv("https://raw.githubusercontent.com/ProfAndersonVanin/FATEC_MINERACAO_DADOS_2SEM2024/main/venda-de-carros.csv")
df_carros

  Fabricante       Cor  Quilometragem  Portas          Preco
0     Toyota    Branco         150043       4   R$ 24,000.00
1      Honda  Vermelho          87899       4   R$ 25,000.00
2     Toyota      Azul          32549       3   R$ 27,000.00
3        BMW     Preto          11179       5  R$ 122,000.00
4     Nissan    Branco         213095       4   R$ 13,500.00
5     Toyota     Verde          99213       4   R$ 14,500.00
6      Honda      Azul          45698       4   R$ 17,500.00
7      Honda      Azul          54738       4   R$ 27,000.00
8     Toyota    Branco          60000       4   R$ 26,250.00
9     Nissan    Branco          31600       4   R$ 19,700.00

## Anatomia de um DataFrame

![image.png]()

# **Explorando os dados**
Uma das primeiras tarefas que fazemos logo após importar os dados para um DataFrame Pandas é começar a explorá-lo. O Pandas possui muitas funções internas que nos permitem obter informações descritivas dos dados, .dtypes por exemplo nos mostra que tipo de dados cada coluna contém:

## Dtypes

In [31]:
df_carros.dtypes

Fabricante       object
Cor              object
Quilometragem     int64
Portas            int64
Preco            object
dtype: object

Note que a coluna Preco não é um número inteiro como Quilometragem e Portas. Não se preocupe isso é fácil de consertar e faremos isso em outro momento.

## Describe
A função `.describe()` nos mostra uma visão estatística de todas as colunas numéricas:

In [32]:
df_carros.describe()

       Quilometragem     Portas
count      10.000000  10.000000
mean    78601.400000   4.000000
std     61983.471735   0.471405
min     11179.000000   3.000000
25%     35836.250000   4.000000
50%     57369.000000   4.000000
75%     96384.500000   4.000000
max    213095.000000   5.000000

## Info
Outra função muito utilizada é a `.info()`, que mostra quantas linhas existem, se há valores ausentes e os tipos de dados de cada coluna:

In [33]:
df_carros.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Fabricante     10 non-null     object
 1   Cor            10 non-null     object
 2   Quilometragem  10 non-null     int64
 3   Portas         10 non-null     int64
 4   Preco          10 non-null     object
dtypes: int64(2), object(3)
memory usage: 528.0+ bytes

## Mean e Sum
Pandas também disponibiliza várias funções estatísticas e matemáticas como `.mean()` e `.sum()` que podem ser aplicadas diretamente em um DataFrame ou Séries.

In [34]:
valores = pd.Series([3000, 3500, 11250])
valores.mean()

5916.666666666667

In [35]:
valores.sum()

17750

## Columns
Usar essas funções em um DataFrame inteiro pode não fazer muito sentido, nesse caso podemos direcionar a função individualmente para uma coluna. O método .columns mostrará todas as colunas de um DataFrame:

In [36]:
df_carros.columns

Index(['Fabricante', 'Cor', 'Quilometragem', 'Portas', 'Preco'], dtype='object')

Selecionando uma coluna com dados numéricos podemos utilizar a função estatística `.mean()` novamente:

In [37]:
df_carros["Quilometragem"].mean()

78601.4

# **Visualizando e selecionando dados**
Na prática, realizar alterações nos dados e visualizá-los constantemente é uma tarefa de rotina. Nem sempre precisamos alterar todos os dados de um DataFrame, portanto veremos maneiras diferentes de selecionar.

## Head
Para visualizar as primeiras 5 linhas do seu DataFrame existe a função `.head()` que é muito utilizada:

In [38]:
# exibindo as primeiras 5 linhas do DataFrame
df_carros.head()

  Fabricante       Cor  Quilometragem  Portas          Preco
0     Toyota    Branco         150043       4   R$ 24,000.00
1      Honda  Vermelho          87899       4   R$ 25,000.00
2     Toyota      Azul          32549       3   R$ 27,000.00
3        BMW     Preto          11179       5  R$ 122,000.00
4     Nissan    Branco         213095       4   R$ 13,500.00

## Tail
Outro método muito utilizado é o `.tail()` que seleciona as últimas 5 linhas do seu DataFrame:

In [39]:
# exibindo as últimas 5 linhas do DataFrame
df_carros.tail()

  Fabricante     Cor  Quilometragem  Portas         Preco
5     Toyota   Verde          99213       4  R$ 14,500.00
6      Honda    Azul          45698       4  R$ 17,500.00
7      Honda    Azul          54738       4  R$ 27,000.00
8     Toyota  Branco          60000       4  R$ 26,250.00
9     Nissan  Branco          31600       4  R$ 19,700.00

Ao selecionar colunas podemos elaborar filtros condicionais entre colchetes, vejamos a sintaxe:

In [40]:
# selecionando carros com quilometragem acima de 100.000
df_carros[df_carros["Quilometragem"] > 100000]

  Fabricante     Cor  Quilometragem  Portas         Preco
0     Toyota  Branco         150043       4  R$ 24,000.00
4     Nissan  Branco         213095       4  R$ 13,500.00

In [41]:
# selecionando apenas os carros da Honda
df_carros[df_carros["Fabricante"] == "Honda"]

  Fabricante       Cor  Quilometragem  Portas         Preco
1      Honda  Vermelho          87899       4  R$ 25,000.00
6      Honda      Azul          45698       4  R$ 17,500.00
7      Honda      Azul          54738       4  R$ 27,000.00

## Groupby
Para comparar mais colunas no contexto de outra coluna, podemos usar o `.groupby()`, por exemplo, podemos agrupar os dados por fabricante e calcular a média das colunas numéricas:

In [42]:
# agrupando os dados pelo fabricante e calculando a média das outras colunas (Quilometragem por exemplo)
df_carros.groupby("Fabricante")['Quilometragem'].mean()

Fabricante
BMW        11179.000000
Honda      62778.333333
Nissan    122347.500000
Toyota     85451.250000
Name: Quilometragem, dtype: float64